export const userDetailsArray = [
    {
      profession: "UI/UX Designer",
      age: "23 Years",
      height: "5 Ft 5 In",
      religious: "Hindu, Nadar",
      maritalStatus: "Never Married",
      spokenLanguage: "Tamil, English",
      location: "Chennai, Tamilnadu, India",
      shortListed: false,
    },
    {
      profession: "Software Engineer",
      age: "27 Years",
      height: "5 Ft 8 In",
      religious: "Christian, Roman Catholic",
      maritalStatus: "Never Married",
      spokenLanguage: "English, Hindi",
      location: "Bangalore, Karnataka, India",
      shortListed: true,
    },
    {
      profession: "Doctor",
      age: "30 Years",
      height: "5 Ft 6 In",
      religious: "Muslim, Sunni",
      maritalStatus: "Divorced",
      spokenLanguage: "Urdu, English",
      location: "Hyderabad, Telangana, India",
      shortListed: false,
    },
    {
      profession: "Teacher",
      age: "26 Years",
      height: "5 Ft 3 In",
      religious: "Hindu, Brahmin",
      maritalStatus: "Never Married",
      spokenLanguage: "Marathi, Hindi",
      location: "Pune, Maharashtra, India",
      shortListed: true,
    },
    {
      profession: "Architect",
      age: "28 Years",
      height: "5 Ft 7 In",
      religious: "Sikh, Khatri",
      maritalStatus: "Never Married",
      spokenLanguage: "Punjabi, English",
      location: "Chandigarh, India",
      shortListed: true,
      
    },
    {
      profession: "Mechanical Engineer",
      age: "25 Years",
      height: "5 Ft 9 In",
      religious: "Hindu, Kshatriya",
      maritalStatus: "Never Married",
      spokenLanguage: "Tamil, Telugu",
      location: "Chennai, Tamilnadu, India",
      shortListed: true,
    },
    {
      profession: "Journalist",
      age: "32 Years",
      height: "5 Ft 4 In",
      religious: "Christian, Protestant",
      maritalStatus: "Widowed",
      spokenLanguage: "English, Malayalam",
      location: "Kochi, Kerala, India",
      shortListed: true,
    },
    {
      profession: "Banker",
      age: "29 Years",
      height: "5 Ft 5 In",
      religious: "Hindu, Vaishya",
      maritalStatus: "Never Married",
      spokenLanguage: "Gujarati, Hindi",
      location: "Ahmedabad, Gujarat, India",
      shortListed: false,
    },
    {
      profession: "Chef",
      age: "27 Years",
      height: "5 Ft 6 In",
      religious: "Hindu, Maratha",
      maritalStatus: "Never Married",
      spokenLanguage: "Marathi, English",
      location: "Mumbai, Maharashtra, India",
    },
    {
      profession: "Civil Engineer",
      age: "26 Years",
      height: "5 Ft 8 In",
      religious: "Muslim, Shia",
      maritalStatus: "Never Married",
      spokenLanguage: "Hindi, Urdu",
      location: "Lucknow, Uttar Pradesh, India",
    },
    {
      profession: "Pharmacist",
      age: "31 Years",
      height: "5 Ft 6 In",
      religious: "Hindu, Nair",
      maritalStatus: "Never Married",
      spokenLanguage: "Malayalam, English",
      location: "Thiruvananthapuram, Kerala, India",
    },
    {
      profession: "Data Scientist",
      age: "28 Years",
      height: "5 Ft 9 In",
      religious: "Hindu, Gupta",
      maritalStatus: "Never Married",
      spokenLanguage: "Hindi, English",
      location: "Delhi, India",
    },
    {
      profession: "Graphic Designer",
      age: "24 Years",
      height: "5 Ft 4 In",
      religious: "Christian, Syro Malabar",
      maritalStatus: "Never Married",
      spokenLanguage: "English, Tamil",
      location: "Coimbatore, Tamilnadu, India",
    },
    {
      profession: "Lawyer",
      age: "29 Years",
      height: "5 Ft 8 In",
      religious: "Hindu, Kayastha",
      maritalStatus: "Never Married",
      spokenLanguage: "Hindi, English",
      location: "Patna, Bihar, India",
    },
    {
      profession: "Nurse",
      age: "26 Years",
      height: "5 Ft 3 In",
      religious: "Christian, Jacobite",
      maritalStatus: "Never Married",
      spokenLanguage: "Malayalam, English",
      location: "Kottayam, Kerala, India",
    },
    {
      profession: "Scientist",
      age: "34 Years",
      height: "5 Ft 7 In",
      religious: "Hindu, Iyer",
      maritalStatus: "Divorced",
      spokenLanguage: "Tamil, Hindi",
      location: "Bangalore, Karnataka, India",
    },
    {
      profession: "Marketing Manager",
      age: "28 Years",
      height: "5 Ft 6 In",
      religious: "Hindu, Reddy",
      maritalStatus: "Never Married",
      spokenLanguage: "Telugu, English",
      location: "Hyderabad, Telangana, India",
    },
    {
      profession: "Software Developer",
      age: "25 Years",
      height: "5 Ft 10 In",
      religious: "Hindu, Jat",
      maritalStatus: "Never Married",
      spokenLanguage: "Punjabi, Hindi",
      location: "Delhi, India",
    },
    {
      profession: "Accountant",
      age: "30 Years",
      height: "5 Ft 5 In",
      religious: "Hindu, Agarwal",
      maritalStatus: "Never Married",
      spokenLanguage: "Hindi, English",
      location: "Jaipur, Rajasthan, India",
    },
    {
      profession: "Artist",
      age: "27 Years",
      height: "5 Ft 6 In",
      religious: "Hindu, Baniya",
      maritalStatus: "Never Married",
      spokenLanguage: "Hindi, English",
      location: "Lucknow, Uttar Pradesh, India",
    },
  ];
  